/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicTiendaRouteImport } from './routes/_public.tienda'
import { Route as PublicTalleresRouteImport } from './routes/_public.talleres'
import { Route as PublicSobreMakranaRouteImport } from './routes/_public.sobre-makrana'
import { Route as PublicRegistroRouteImport } from './routes/_public.registro'
import { Route as PublicLibroDeReclamacionesRouteImport } from './routes/_public.libro-de-reclamaciones'
import { Route as PublicContactoRouteImport } from './routes/_public.contacto'
import { Route as PublicCheckoutRouteImport } from './routes/_public.checkout'
import { Route as PublicCarritoRouteImport } from './routes/_public.carrito'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PublicNovedadesIndexRouteImport } from './routes/_public.novedades.index'
import { Route as PublicCatalogoIndexRouteImport } from './routes/_public.catalogo.index'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated/cliente.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as PublicPedidoCodeRouteImport } from './routes/_public.pedido.$code'
import { Route as PublicPagoRetornoRouteImport } from './routes/_public.pago.retorno'
import { Route as PublicNovedadesSlugRouteImport } from './routes/_public.novedades.$slug'
import { Route as PublicCheckoutPagoRouteImport } from './routes/_public.checkout.pago'
import { Route as PublicCatalogoSlugRouteImport } from './routes/_public.catalogo.$slug'
import { Route as AuthenticatedClienteTalleresRouteImport } from './routes/_authenticated/cliente.talleres'
import { Route as AuthenticatedClientePerfilRouteImport } from './routes/_authenticated/cliente.perfil'
import { Route as AuthenticatedClientePedidosRouteImport } from './routes/_authenticated/cliente.pedidos'
import { Route as AuthenticatedClienteCursosRouteImport } from './routes/_authenticated/cliente.cursos'
import { Route as AuthenticatedClienteComprobantesRouteImport } from './routes/_authenticated/cliente.comprobantes'
import { Route as AuthenticatedAdminVentasRouteImport } from './routes/_authenticated/admin.ventas'
import { Route as AuthenticatedAdminTributosRouteImport } from './routes/_authenticated/admin.tributos'
import { Route as AuthenticatedAdminTalleresRouteImport } from './routes/_authenticated/admin.talleres'
import { Route as AuthenticatedAdminSireRouteImport } from './routes/_authenticated/admin.sire'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated/admin.reportes'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin.productos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminPagosRouteImport } from './routes/_authenticated/admin.pagos'
import { Route as AuthenticatedAdminPaginaWebRouteImport } from './routes/_authenticated/admin.pagina-web'
import { Route as AuthenticatedAdminNovedadesRouteImport } from './routes/_authenticated/admin.novedades'
import { Route as AuthenticatedAdminMovimientosRouteImport } from './routes/_authenticated/admin.movimientos'
import { Route as AuthenticatedAdminMaterialesRouteImport } from './routes/_authenticated/admin.materiales'
import { Route as AuthenticatedAdminManualRouteImport } from './routes/_authenticated/admin.manual'
import { Route as AuthenticatedAdminFeriasRouteImport } from './routes/_authenticated/admin.ferias'
import { Route as AuthenticatedAdminCotizacionesRouteImport } from './routes/_authenticated/admin.cotizaciones'
import { Route as AuthenticatedAdminConfiguracionRouteImport } from './routes/_authenticated/admin.configuracion'
import { Route as AuthenticatedAdminComprobantesRouteImport } from './routes/_authenticated/admin.comprobantes'
import { Route as AuthenticatedAdminComprasRouteImport } from './routes/_authenticated/admin.compras'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin.calendario'
import { Route as AuthenticatedAdminAlmacenesRouteImport } from './routes/_authenticated/admin.almacenes'
import { Route as AuthenticatedAdminPedidosOrderIdRouteImport } from './routes/_authenticated/admin.pedidos.$orderId'
import { Route as AuthenticatedAdminConfiguracionTributariaRouteImport } from './routes/_authenticated/admin.configuracion.tributaria'
import { Route as AuthenticatedAdminConfiguracionComercioRouteImport } from './routes/_authenticated/admin.configuracion.comercio'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTiendaRoute = PublicTiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTalleresRoute = PublicTalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSobreMakranaRoute = PublicSobreMakranaRouteImport.update({
  id: '/sobre-makrana',
  path: '/sobre-makrana',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegistroRoute = PublicRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLibroDeReclamacionesRoute =
  PublicLibroDeReclamacionesRouteImport.update({
    id: '/libro-de-reclamaciones',
    path: '/libro-de-reclamaciones',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicContactoRoute = PublicContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCarritoRoute = PublicCarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicNovedadesIndexRoute = PublicNovedadesIndexRouteImport.update({
  id: '/novedades/',
  path: '/novedades/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCatalogoIndexRoute = PublicCatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PublicPedidoCodeRoute = PublicPedidoCodeRouteImport.update({
  id: '/pedido/$code',
  path: '/pedido/$code',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPagoRetornoRoute = PublicPagoRetornoRouteImport.update({
  id: '/pago/retorno',
  path: '/pago/retorno',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNovedadesSlugRoute = PublicNovedadesSlugRouteImport.update({
  id: '/novedades/$slug',
  path: '/novedades/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutPagoRoute = PublicCheckoutPagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => PublicCheckoutRoute,
} as any)
const PublicCatalogoSlugRoute = PublicCatalogoSlugRouteImport.update({
  id: '/catalogo/$slug',
  path: '/catalogo/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedClienteTalleresRoute =
  AuthenticatedClienteTalleresRouteImport.update({
    id: '/talleres',
    path: '/talleres',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePerfilRoute =
  AuthenticatedClientePerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClientePedidosRoute =
  AuthenticatedClientePedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteCursosRoute =
  AuthenticatedClienteCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteComprobantesRoute =
  AuthenticatedClienteComprobantesRouteImport.update({
    id: '/comprobantes',
    path: '/comprobantes',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminVentasRoute =
  AuthenticatedAdminVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTributosRoute =
  AuthenticatedAdminTributosRouteImport.update({
    id: '/tributos',
    path: '/tributos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTalleresRoute =
  AuthenticatedAdminTalleresRouteImport.update({
    id: '/talleres',
    path: '/talleres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSireRoute = AuthenticatedAdminSireRouteImport.update({
  id: '/sire',
  path: '/sire',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagosRoute = AuthenticatedAdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaginaWebRoute =
  AuthenticatedAdminPaginaWebRouteImport.update({
    id: '/pagina-web',
    path: '/pagina-web',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNovedadesRoute =
  AuthenticatedAdminNovedadesRouteImport.update({
    id: '/novedades',
    path: '/novedades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMovimientosRoute =
  AuthenticatedAdminMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaterialesRoute =
  AuthenticatedAdminMaterialesRouteImport.update({
    id: '/materiales',
    path: '/materiales',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManualRoute =
  AuthenticatedAdminManualRouteImport.update({
    id: '/manual',
    path: '/manual',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeriasRoute =
  AuthenticatedAdminFeriasRouteImport.update({
    id: '/ferias',
    path: '/ferias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCotizacionesRoute =
  AuthenticatedAdminCotizacionesRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracionRoute =
  AuthenticatedAdminConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComprobantesRoute =
  AuthenticatedAdminComprobantesRouteImport.update({
    id: '/comprobantes',
    path: '/comprobantes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComprasRoute =
  AuthenticatedAdminComprasRouteImport.update({
    id: '/compras',
    path: '/compras',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlmacenesRoute =
  AuthenticatedAdminAlmacenesRouteImport.update({
    id: '/almacenes',
    path: '/almacenes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosOrderIdRoute =
  AuthenticatedAdminPedidosOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAdminPedidosRoute,
  } as any)
const AuthenticatedAdminConfiguracionTributariaRoute =
  AuthenticatedAdminConfiguracionTributariaRouteImport.update({
    id: '/tributaria',
    path: '/tributaria',
    getParentRoute: () => AuthenticatedAdminConfiguracionRoute,
  } as any)
const AuthenticatedAdminConfiguracionComercioRoute =
  AuthenticatedAdminConfiguracionComercioRouteImport.update({
    id: '/comercio',
    path: '/comercio',
    getParentRoute: () => AuthenticatedAdminConfiguracionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/plataforma': typeof PlataformaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/carrito': typeof PublicCarritoRoute
  '/checkout': typeof PublicCheckoutRouteWithChildren
  '/contacto': typeof PublicContactoRoute
  '/libro-de-reclamaciones': typeof PublicLibroDeReclamacionesRoute
  '/registro': typeof PublicRegistroRoute
  '/sobre-makrana': typeof PublicSobreMakranaRoute
  '/talleres': typeof PublicTalleresRoute
  '/tienda': typeof PublicTiendaRoute
  '/admin/almacenes': typeof AuthenticatedAdminAlmacenesRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/admin/comprobantes': typeof AuthenticatedAdminComprobantesRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRouteWithChildren
  '/admin/cotizaciones': typeof AuthenticatedAdminCotizacionesRoute
  '/admin/ferias': typeof AuthenticatedAdminFeriasRoute
  '/admin/manual': typeof AuthenticatedAdminManualRoute
  '/admin/materiales': typeof AuthenticatedAdminMaterialesRoute
  '/admin/movimientos': typeof AuthenticatedAdminMovimientosRoute
  '/admin/novedades': typeof AuthenticatedAdminNovedadesRoute
  '/admin/pagina-web': typeof AuthenticatedAdminPaginaWebRoute
  '/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/sire': typeof AuthenticatedAdminSireRoute
  '/admin/talleres': typeof AuthenticatedAdminTalleresRoute
  '/admin/tributos': typeof AuthenticatedAdminTributosRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/cliente/comprobantes': typeof AuthenticatedClienteComprobantesRoute
  '/cliente/cursos': typeof AuthenticatedClienteCursosRoute
  '/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/cliente/perfil': typeof AuthenticatedClientePerfilRoute
  '/cliente/talleres': typeof AuthenticatedClienteTalleresRoute
  '/catalogo/$slug': typeof PublicCatalogoSlugRoute
  '/checkout/pago': typeof PublicCheckoutPagoRoute
  '/novedades/$slug': typeof PublicNovedadesSlugRoute
  '/pago/retorno': typeof PublicPagoRetornoRoute
  '/pedido/$code': typeof PublicPedidoCodeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/catalogo/': typeof PublicCatalogoIndexRoute
  '/novedades/': typeof PublicNovedadesIndexRoute
  '/admin/configuracion/comercio': typeof AuthenticatedAdminConfiguracionComercioRoute
  '/admin/configuracion/tributaria': typeof AuthenticatedAdminConfiguracionTributariaRoute
  '/admin/pedidos/$orderId': typeof AuthenticatedAdminPedidosOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/plataforma': typeof PlataformaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/carrito': typeof PublicCarritoRoute
  '/checkout': typeof PublicCheckoutRouteWithChildren
  '/contacto': typeof PublicContactoRoute
  '/libro-de-reclamaciones': typeof PublicLibroDeReclamacionesRoute
  '/registro': typeof PublicRegistroRoute
  '/sobre-makrana': typeof PublicSobreMakranaRoute
  '/talleres': typeof PublicTalleresRoute
  '/tienda': typeof PublicTiendaRoute
  '/admin/almacenes': typeof AuthenticatedAdminAlmacenesRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/admin/comprobantes': typeof AuthenticatedAdminComprobantesRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRouteWithChildren
  '/admin/cotizaciones': typeof AuthenticatedAdminCotizacionesRoute
  '/admin/ferias': typeof AuthenticatedAdminFeriasRoute
  '/admin/manual': typeof AuthenticatedAdminManualRoute
  '/admin/materiales': typeof AuthenticatedAdminMaterialesRoute
  '/admin/movimientos': typeof AuthenticatedAdminMovimientosRoute
  '/admin/novedades': typeof AuthenticatedAdminNovedadesRoute
  '/admin/pagina-web': typeof AuthenticatedAdminPaginaWebRoute
  '/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/sire': typeof AuthenticatedAdminSireRoute
  '/admin/talleres': typeof AuthenticatedAdminTalleresRoute
  '/admin/tributos': typeof AuthenticatedAdminTributosRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/cliente/comprobantes': typeof AuthenticatedClienteComprobantesRoute
  '/cliente/cursos': typeof AuthenticatedClienteCursosRoute
  '/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/cliente/perfil': typeof AuthenticatedClientePerfilRoute
  '/cliente/talleres': typeof AuthenticatedClienteTalleresRoute
  '/catalogo/$slug': typeof PublicCatalogoSlugRoute
  '/checkout/pago': typeof PublicCheckoutPagoRoute
  '/novedades/$slug': typeof PublicNovedadesSlugRoute
  '/pago/retorno': typeof PublicPagoRetornoRoute
  '/pedido/$code': typeof PublicPedidoCodeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/catalogo': typeof PublicCatalogoIndexRoute
  '/novedades': typeof PublicNovedadesIndexRoute
  '/admin/configuracion/comercio': typeof AuthenticatedAdminConfiguracionComercioRoute
  '/admin/configuracion/tributaria': typeof AuthenticatedAdminConfiguracionTributariaRoute
  '/admin/pedidos/$orderId': typeof AuthenticatedAdminPedidosOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/plataforma': typeof PlataformaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/_public/carrito': typeof PublicCarritoRoute
  '/_public/checkout': typeof PublicCheckoutRouteWithChildren
  '/_public/contacto': typeof PublicContactoRoute
  '/_public/libro-de-reclamaciones': typeof PublicLibroDeReclamacionesRoute
  '/_public/registro': typeof PublicRegistroRoute
  '/_public/sobre-makrana': typeof PublicSobreMakranaRoute
  '/_public/talleres': typeof PublicTalleresRoute
  '/_public/tienda': typeof PublicTiendaRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/admin/almacenes': typeof AuthenticatedAdminAlmacenesRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/_authenticated/admin/comprobantes': typeof AuthenticatedAdminComprobantesRoute
  '/_authenticated/admin/configuracion': typeof AuthenticatedAdminConfiguracionRouteWithChildren
  '/_authenticated/admin/cotizaciones': typeof AuthenticatedAdminCotizacionesRoute
  '/_authenticated/admin/ferias': typeof AuthenticatedAdminFeriasRoute
  '/_authenticated/admin/manual': typeof AuthenticatedAdminManualRoute
  '/_authenticated/admin/materiales': typeof AuthenticatedAdminMaterialesRoute
  '/_authenticated/admin/movimientos': typeof AuthenticatedAdminMovimientosRoute
  '/_authenticated/admin/novedades': typeof AuthenticatedAdminNovedadesRoute
  '/_authenticated/admin/pagina-web': typeof AuthenticatedAdminPaginaWebRoute
  '/_authenticated/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/sire': typeof AuthenticatedAdminSireRoute
  '/_authenticated/admin/talleres': typeof AuthenticatedAdminTalleresRoute
  '/_authenticated/admin/tributos': typeof AuthenticatedAdminTributosRoute
  '/_authenticated/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/_authenticated/cliente/comprobantes': typeof AuthenticatedClienteComprobantesRoute
  '/_authenticated/cliente/cursos': typeof AuthenticatedClienteCursosRoute
  '/_authenticated/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/_authenticated/cliente/perfil': typeof AuthenticatedClientePerfilRoute
  '/_authenticated/cliente/talleres': typeof AuthenticatedClienteTalleresRoute
  '/_public/catalogo/$slug': typeof PublicCatalogoSlugRoute
  '/_public/checkout/pago': typeof PublicCheckoutPagoRoute
  '/_public/novedades/$slug': typeof PublicNovedadesSlugRoute
  '/_public/pago/retorno': typeof PublicPagoRetornoRoute
  '/_public/pedido/$code': typeof PublicPedidoCodeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_public/catalogo/': typeof PublicCatalogoIndexRoute
  '/_public/novedades/': typeof PublicNovedadesIndexRoute
  '/_authenticated/admin/configuracion/comercio': typeof AuthenticatedAdminConfiguracionComercioRoute
  '/_authenticated/admin/configuracion/tributaria': typeof AuthenticatedAdminConfiguracionTributariaRoute
  '/_authenticated/admin/pedidos/$orderId': typeof AuthenticatedAdminPedidosOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/plataforma'
    | '/sitemap.xml'
    | '/admin'
    | '/cliente'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/libro-de-reclamaciones'
    | '/registro'
    | '/sobre-makrana'
    | '/talleres'
    | '/tienda'
    | '/admin/almacenes'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/compras'
    | '/admin/comprobantes'
    | '/admin/configuracion'
    | '/admin/cotizaciones'
    | '/admin/ferias'
    | '/admin/manual'
    | '/admin/materiales'
    | '/admin/movimientos'
    | '/admin/novedades'
    | '/admin/pagina-web'
    | '/admin/pagos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/sire'
    | '/admin/talleres'
    | '/admin/tributos'
    | '/admin/ventas'
    | '/cliente/comprobantes'
    | '/cliente/cursos'
    | '/cliente/pedidos'
    | '/cliente/perfil'
    | '/cliente/talleres'
    | '/catalogo/$slug'
    | '/checkout/pago'
    | '/novedades/$slug'
    | '/pago/retorno'
    | '/pedido/$code'
    | '/admin/'
    | '/cliente/'
    | '/catalogo/'
    | '/novedades/'
    | '/admin/configuracion/comercio'
    | '/admin/configuracion/tributaria'
    | '/admin/pedidos/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/plataforma'
    | '/sitemap.xml'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/libro-de-reclamaciones'
    | '/registro'
    | '/sobre-makrana'
    | '/talleres'
    | '/tienda'
    | '/admin/almacenes'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/compras'
    | '/admin/comprobantes'
    | '/admin/configuracion'
    | '/admin/cotizaciones'
    | '/admin/ferias'
    | '/admin/manual'
    | '/admin/materiales'
    | '/admin/movimientos'
    | '/admin/novedades'
    | '/admin/pagina-web'
    | '/admin/pagos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/sire'
    | '/admin/talleres'
    | '/admin/tributos'
    | '/admin/ventas'
    | '/cliente/comprobantes'
    | '/cliente/cursos'
    | '/cliente/pedidos'
    | '/cliente/perfil'
    | '/cliente/talleres'
    | '/catalogo/$slug'
    | '/checkout/pago'
    | '/novedades/$slug'
    | '/pago/retorno'
    | '/pedido/$code'
    | '/admin'
    | '/cliente'
    | '/catalogo'
    | '/novedades'
    | '/admin/configuracion/comercio'
    | '/admin/configuracion/tributaria'
    | '/admin/pedidos/$orderId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/plataforma'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/cliente'
    | '/_public/carrito'
    | '/_public/checkout'
    | '/_public/contacto'
    | '/_public/libro-de-reclamaciones'
    | '/_public/registro'
    | '/_public/sobre-makrana'
    | '/_public/talleres'
    | '/_public/tienda'
    | '/_public/'
    | '/_authenticated/admin/almacenes'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/compras'
    | '/_authenticated/admin/comprobantes'
    | '/_authenticated/admin/configuracion'
    | '/_authenticated/admin/cotizaciones'
    | '/_authenticated/admin/ferias'
    | '/_authenticated/admin/manual'
    | '/_authenticated/admin/materiales'
    | '/_authenticated/admin/movimientos'
    | '/_authenticated/admin/novedades'
    | '/_authenticated/admin/pagina-web'
    | '/_authenticated/admin/pagos'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/sire'
    | '/_authenticated/admin/talleres'
    | '/_authenticated/admin/tributos'
    | '/_authenticated/admin/ventas'
    | '/_authenticated/cliente/comprobantes'
    | '/_authenticated/cliente/cursos'
    | '/_authenticated/cliente/pedidos'
    | '/_authenticated/cliente/perfil'
    | '/_authenticated/cliente/talleres'
    | '/_public/catalogo/$slug'
    | '/_public/checkout/pago'
    | '/_public/novedades/$slug'
    | '/_public/pago/retorno'
    | '/_public/pedido/$code'
    | '/_authenticated/admin/'
    | '/_authenticated/cliente/'
    | '/_public/catalogo/'
    | '/_public/novedades/'
    | '/_authenticated/admin/configuracion/comercio'
    | '/_authenticated/admin/configuracion/tributaria'
    | '/_authenticated/admin/pedidos/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlataformaRoute: typeof PlataformaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tienda': {
      id: '/_public/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof PublicTiendaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/talleres': {
      id: '/_public/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof PublicTalleresRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sobre-makrana': {
      id: '/_public/sobre-makrana'
      path: '/sobre-makrana'
      fullPath: '/sobre-makrana'
      preLoaderRoute: typeof PublicSobreMakranaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/registro': {
      id: '/_public/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof PublicRegistroRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/libro-de-reclamaciones': {
      id: '/_public/libro-de-reclamaciones'
      path: '/libro-de-reclamaciones'
      fullPath: '/libro-de-reclamaciones'
      preLoaderRoute: typeof PublicLibroDeReclamacionesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contacto': {
      id: '/_public/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof PublicContactoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/carrito': {
      id: '/_public/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof PublicCarritoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/novedades/': {
      id: '/_public/novedades/'
      path: '/novedades'
      fullPath: '/novedades/'
      preLoaderRoute: typeof PublicNovedadesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/catalogo/': {
      id: '/_public/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof PublicCatalogoIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_public/pedido/$code': {
      id: '/_public/pedido/$code'
      path: '/pedido/$code'
      fullPath: '/pedido/$code'
      preLoaderRoute: typeof PublicPedidoCodeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pago/retorno': {
      id: '/_public/pago/retorno'
      path: '/pago/retorno'
      fullPath: '/pago/retorno'
      preLoaderRoute: typeof PublicPagoRetornoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/novedades/$slug': {
      id: '/_public/novedades/$slug'
      path: '/novedades/$slug'
      fullPath: '/novedades/$slug'
      preLoaderRoute: typeof PublicNovedadesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout/pago': {
      id: '/_public/checkout/pago'
      path: '/pago'
      fullPath: '/checkout/pago'
      preLoaderRoute: typeof PublicCheckoutPagoRouteImport
      parentRoute: typeof PublicCheckoutRoute
    }
    '/_public/catalogo/$slug': {
      id: '/_public/catalogo/$slug'
      path: '/catalogo/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof PublicCatalogoSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/cliente/talleres': {
      id: '/_authenticated/cliente/talleres'
      path: '/talleres'
      fullPath: '/cliente/talleres'
      preLoaderRoute: typeof AuthenticatedClienteTalleresRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/perfil': {
      id: '/_authenticated/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof AuthenticatedClientePerfilRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/pedidos': {
      id: '/_authenticated/cliente/pedidos'
      path: '/pedidos'
      fullPath: '/cliente/pedidos'
      preLoaderRoute: typeof AuthenticatedClientePedidosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/cursos': {
      id: '/_authenticated/cliente/cursos'
      path: '/cursos'
      fullPath: '/cliente/cursos'
      preLoaderRoute: typeof AuthenticatedClienteCursosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/comprobantes': {
      id: '/_authenticated/cliente/comprobantes'
      path: '/comprobantes'
      fullPath: '/cliente/comprobantes'
      preLoaderRoute: typeof AuthenticatedClienteComprobantesRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/ventas': {
      id: '/_authenticated/admin/ventas'
      path: '/ventas'
      fullPath: '/admin/ventas'
      preLoaderRoute: typeof AuthenticatedAdminVentasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tributos': {
      id: '/_authenticated/admin/tributos'
      path: '/tributos'
      fullPath: '/admin/tributos'
      preLoaderRoute: typeof AuthenticatedAdminTributosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/talleres': {
      id: '/_authenticated/admin/talleres'
      path: '/talleres'
      fullPath: '/admin/talleres'
      preLoaderRoute: typeof AuthenticatedAdminTalleresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sire': {
      id: '/_authenticated/admin/sire'
      path: '/sire'
      fullPath: '/admin/sire'
      preLoaderRoute: typeof AuthenticatedAdminSireRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagos': {
      id: '/_authenticated/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AuthenticatedAdminPagosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagina-web': {
      id: '/_authenticated/admin/pagina-web'
      path: '/pagina-web'
      fullPath: '/admin/pagina-web'
      preLoaderRoute: typeof AuthenticatedAdminPaginaWebRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/novedades': {
      id: '/_authenticated/admin/novedades'
      path: '/novedades'
      fullPath: '/admin/novedades'
      preLoaderRoute: typeof AuthenticatedAdminNovedadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/movimientos': {
      id: '/_authenticated/admin/movimientos'
      path: '/movimientos'
      fullPath: '/admin/movimientos'
      preLoaderRoute: typeof AuthenticatedAdminMovimientosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/materiales': {
      id: '/_authenticated/admin/materiales'
      path: '/materiales'
      fullPath: '/admin/materiales'
      preLoaderRoute: typeof AuthenticatedAdminMaterialesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/manual': {
      id: '/_authenticated/admin/manual'
      path: '/manual'
      fullPath: '/admin/manual'
      preLoaderRoute: typeof AuthenticatedAdminManualRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ferias': {
      id: '/_authenticated/admin/ferias'
      path: '/ferias'
      fullPath: '/admin/ferias'
      preLoaderRoute: typeof AuthenticatedAdminFeriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cotizaciones': {
      id: '/_authenticated/admin/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/admin/cotizaciones'
      preLoaderRoute: typeof AuthenticatedAdminCotizacionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracion': {
      id: '/_authenticated/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comprobantes': {
      id: '/_authenticated/admin/comprobantes'
      path: '/comprobantes'
      fullPath: '/admin/comprobantes'
      preLoaderRoute: typeof AuthenticatedAdminComprobantesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/compras': {
      id: '/_authenticated/admin/compras'
      path: '/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AuthenticatedAdminComprasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/almacenes': {
      id: '/_authenticated/admin/almacenes'
      path: '/almacenes'
      fullPath: '/admin/almacenes'
      preLoaderRoute: typeof AuthenticatedAdminAlmacenesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos/$orderId': {
      id: '/_authenticated/admin/pedidos/$orderId'
      path: '/$orderId'
      fullPath: '/admin/pedidos/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminPedidosOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminPedidosRoute
    }
    '/_authenticated/admin/configuracion/tributaria': {
      id: '/_authenticated/admin/configuracion/tributaria'
      path: '/tributaria'
      fullPath: '/admin/configuracion/tributaria'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionTributariaRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracionRoute
    }
    '/_authenticated/admin/configuracion/comercio': {
      id: '/_authenticated/admin/configuracion/comercio'
      path: '/comercio'
      fullPath: '/admin/configuracion/comercio'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionComercioRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracionRoute
    }
  }
}

interface AuthenticatedAdminConfiguracionRouteChildren {
  AuthenticatedAdminConfiguracionComercioRoute: typeof AuthenticatedAdminConfiguracionComercioRoute
  AuthenticatedAdminConfiguracionTributariaRoute: typeof AuthenticatedAdminConfiguracionTributariaRoute
}

const AuthenticatedAdminConfiguracionRouteChildren: AuthenticatedAdminConfiguracionRouteChildren =
  {
    AuthenticatedAdminConfiguracionComercioRoute:
      AuthenticatedAdminConfiguracionComercioRoute,
    AuthenticatedAdminConfiguracionTributariaRoute:
      AuthenticatedAdminConfiguracionTributariaRoute,
  }

const AuthenticatedAdminConfiguracionRouteWithChildren =
  AuthenticatedAdminConfiguracionRoute._addFileChildren(
    AuthenticatedAdminConfiguracionRouteChildren,
  )

interface AuthenticatedAdminPedidosRouteChildren {
  AuthenticatedAdminPedidosOrderIdRoute: typeof AuthenticatedAdminPedidosOrderIdRoute
}

const AuthenticatedAdminPedidosRouteChildren: AuthenticatedAdminPedidosRouteChildren =
  {
    AuthenticatedAdminPedidosOrderIdRoute:
      AuthenticatedAdminPedidosOrderIdRoute,
  }

const AuthenticatedAdminPedidosRouteWithChildren =
  AuthenticatedAdminPedidosRoute._addFileChildren(
    AuthenticatedAdminPedidosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlmacenesRoute: typeof AuthenticatedAdminAlmacenesRoute
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminComprasRoute: typeof AuthenticatedAdminComprasRoute
  AuthenticatedAdminComprobantesRoute: typeof AuthenticatedAdminComprobantesRoute
  AuthenticatedAdminConfiguracionRoute: typeof AuthenticatedAdminConfiguracionRouteWithChildren
  AuthenticatedAdminCotizacionesRoute: typeof AuthenticatedAdminCotizacionesRoute
  AuthenticatedAdminFeriasRoute: typeof AuthenticatedAdminFeriasRoute
  AuthenticatedAdminManualRoute: typeof AuthenticatedAdminManualRoute
  AuthenticatedAdminMaterialesRoute: typeof AuthenticatedAdminMaterialesRoute
  AuthenticatedAdminMovimientosRoute: typeof AuthenticatedAdminMovimientosRoute
  AuthenticatedAdminNovedadesRoute: typeof AuthenticatedAdminNovedadesRoute
  AuthenticatedAdminPaginaWebRoute: typeof AuthenticatedAdminPaginaWebRoute
  AuthenticatedAdminPagosRoute: typeof AuthenticatedAdminPagosRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRouteWithChildren
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminSireRoute: typeof AuthenticatedAdminSireRoute
  AuthenticatedAdminTalleresRoute: typeof AuthenticatedAdminTalleresRoute
  AuthenticatedAdminTributosRoute: typeof AuthenticatedAdminTributosRoute
  AuthenticatedAdminVentasRoute: typeof AuthenticatedAdminVentasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlmacenesRoute: AuthenticatedAdminAlmacenesRoute,
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminComprasRoute: AuthenticatedAdminComprasRoute,
  AuthenticatedAdminComprobantesRoute: AuthenticatedAdminComprobantesRoute,
  AuthenticatedAdminConfiguracionRoute:
    AuthenticatedAdminConfiguracionRouteWithChildren,
  AuthenticatedAdminCotizacionesRoute: AuthenticatedAdminCotizacionesRoute,
  AuthenticatedAdminFeriasRoute: AuthenticatedAdminFeriasRoute,
  AuthenticatedAdminManualRoute: AuthenticatedAdminManualRoute,
  AuthenticatedAdminMaterialesRoute: AuthenticatedAdminMaterialesRoute,
  AuthenticatedAdminMovimientosRoute: AuthenticatedAdminMovimientosRoute,
  AuthenticatedAdminNovedadesRoute: AuthenticatedAdminNovedadesRoute,
  AuthenticatedAdminPaginaWebRoute: AuthenticatedAdminPaginaWebRoute,
  AuthenticatedAdminPagosRoute: AuthenticatedAdminPagosRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRouteWithChildren,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminSireRoute: AuthenticatedAdminSireRoute,
  AuthenticatedAdminTalleresRoute: AuthenticatedAdminTalleresRoute,
  AuthenticatedAdminTributosRoute: AuthenticatedAdminTributosRoute,
  AuthenticatedAdminVentasRoute: AuthenticatedAdminVentasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClienteRouteChildren {
  AuthenticatedClienteComprobantesRoute: typeof AuthenticatedClienteComprobantesRoute
  AuthenticatedClienteCursosRoute: typeof AuthenticatedClienteCursosRoute
  AuthenticatedClientePedidosRoute: typeof AuthenticatedClientePedidosRoute
  AuthenticatedClientePerfilRoute: typeof AuthenticatedClientePerfilRoute
  AuthenticatedClienteTalleresRoute: typeof AuthenticatedClienteTalleresRoute
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
}

const AuthenticatedClienteRouteChildren: AuthenticatedClienteRouteChildren = {
  AuthenticatedClienteComprobantesRoute: AuthenticatedClienteComprobantesRoute,
  AuthenticatedClienteCursosRoute: AuthenticatedClienteCursosRoute,
  AuthenticatedClientePedidosRoute: AuthenticatedClientePedidosRoute,
  AuthenticatedClientePerfilRoute: AuthenticatedClientePerfilRoute,
  AuthenticatedClienteTalleresRoute: AuthenticatedClienteTalleresRoute,
  AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
}

const AuthenticatedClienteRouteWithChildren =
  AuthenticatedClienteRoute._addFileChildren(AuthenticatedClienteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClienteRoute: AuthenticatedClienteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicCheckoutRouteChildren {
  PublicCheckoutPagoRoute: typeof PublicCheckoutPagoRoute
}

const PublicCheckoutRouteChildren: PublicCheckoutRouteChildren = {
  PublicCheckoutPagoRoute: PublicCheckoutPagoRoute,
}

const PublicCheckoutRouteWithChildren = PublicCheckoutRoute._addFileChildren(
  PublicCheckoutRouteChildren,
)

interface PublicRouteChildren {
  PublicCarritoRoute: typeof PublicCarritoRoute
  PublicCheckoutRoute: typeof PublicCheckoutRouteWithChildren
  PublicContactoRoute: typeof PublicContactoRoute
  PublicLibroDeReclamacionesRoute: typeof PublicLibroDeReclamacionesRoute
  PublicRegistroRoute: typeof PublicRegistroRoute
  PublicSobreMakranaRoute: typeof PublicSobreMakranaRoute
  PublicTalleresRoute: typeof PublicTalleresRoute
  PublicTiendaRoute: typeof PublicTiendaRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCatalogoSlugRoute: typeof PublicCatalogoSlugRoute
  PublicNovedadesSlugRoute: typeof PublicNovedadesSlugRoute
  PublicPagoRetornoRoute: typeof PublicPagoRetornoRoute
  PublicPedidoCodeRoute: typeof PublicPedidoCodeRoute
  PublicCatalogoIndexRoute: typeof PublicCatalogoIndexRoute
  PublicNovedadesIndexRoute: typeof PublicNovedadesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCarritoRoute: PublicCarritoRoute,
  PublicCheckoutRoute: PublicCheckoutRouteWithChildren,
  PublicContactoRoute: PublicContactoRoute,
  PublicLibroDeReclamacionesRoute: PublicLibroDeReclamacionesRoute,
  PublicRegistroRoute: PublicRegistroRoute,
  PublicSobreMakranaRoute: PublicSobreMakranaRoute,
  PublicTalleresRoute: PublicTalleresRoute,
  PublicTiendaRoute: PublicTiendaRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCatalogoSlugRoute: PublicCatalogoSlugRoute,
  PublicNovedadesSlugRoute: PublicNovedadesSlugRoute,
  PublicPagoRetornoRoute: PublicPagoRetornoRoute,
  PublicPedidoCodeRoute: PublicPedidoCodeRoute,
  PublicCatalogoIndexRoute: PublicCatalogoIndexRoute,
  PublicNovedadesIndexRoute: PublicNovedadesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
  PlataformaRoute: PlataformaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
